# Generated by Django 3.2.12 on 2022-03-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='data_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
