# Generated by Django 3.2.12 on 2022-03-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_business_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='data_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
