# Generated by Django 3.2.12 on 2022-03-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
