# Generated by Django 3.2.12 on 2022-03-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reguser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
