# Generated by Django 3.2.12 on 2022-03-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emailaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccounts',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccounts',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
