# Generated by Django 3.2.12 on 2022-03-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220306_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccounts',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.reguser'),
            preserve_default=False,
        ),
    ]
