# Generated by Django 3.2.12 on 2022-03-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_emailaccounts_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('status', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emailaccounts')),
            ],
        ),
    ]
