# Generated by Django 3.2.12 on 2022-03-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_raterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raterequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
