# Generated by Django 3.2.12 on 2022-03-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_raterequest_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('rating', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
                ('regUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.reguser')),
            ],
        ),
    ]
