# Generated by Django 3.2.12 on 2022-03-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_realreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realreview',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
