# Generated by Django 3.2.12 on 2022-04-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_realreview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='raterequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
