# Generated by Django 3.2.12 on 2022-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_business_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='url',
            field=models.CharField(default='#', max_length=1000),
            preserve_default=False,
        ),
    ]
